insert into constant
values ('MIN_TRANSFER', 'Số tiền tối thiểu cho mỗi giao dịch chuyển tiền', 100),
       ('MAX_TRANSFER', 'Số tiền tối đa cho dịch vụ chuyển tiền', 1000000000),
       ('MIN_WITHDRAW', 'Số tiền tối thiểu khi rút tiền', 10000),
       ('MAX_WITHDRAW', 'Số tiền tối đa khi rút tiền', 1000000000),
       ('MIN_TOP_UP', 'Số tiền tối thiểu khi nạp tiền vào ví', 10000),
       ('ORDER_TIMEOUT', 'Thời gian tối đa chờ cho giao dịch hoàn tất (min)', 10),
       ('MAX_TOP_UP', 'Số tiền tối đa khi nạp tiền vào ví', 1000000000),
       ('MAX_TRANSFER_PER_DAY', 'Số tiền tối đa cho mỗi giao dịch chuyển tiền trong ngày', 1000000000);



INSERT INTO banks ("id", "name", "code", "bin", "short_name", "logo", transfer_supported, lookup_supported,
                   "support", is_transfer, "swift_code")
VALUES (17, 'Ngân hàng TMCP Công thương Việt Nam', 'ICB', '970415', 'VietinBank', 'https://api.vietqr.io/img/ICB.png',
        1, 1, 3, 1, 'ICBVVNVX'),
       (43, 'Ngân hàng TMCP Ngoại Thương Việt Nam', 'VCB', '970436', 'Vietcombank',
        'https://api.vietqr.io/img/VCB.png', 1, 1, 3, 1, 'BFTVVNVX'),
       (4, 'Ngân hàng TMCP Đầu tư và Phát triển Việt Nam', 'BIDV', '970418', 'BIDV',
        'https://api.vietqr.io/img/BIDV.png', 1, 1, 3, 1, 'BIDVVNVX'),
       (42, 'Ngân hàng Nông nghiệp và Phát triển Nông thôn Việt Nam', 'VBA', '970405', 'Agribank',
        'https://api.vietqr.io/img/VBA.png', 1, 1, 3, 1, 'VBAAVNVX'),
       (26, 'Ngân hàng TMCP Phương Đông', 'OCB', '970448', 'OCB', 'https://api.vietqr.io/img/OCB.png', 1, 1, 3,
        1, 'ORCOVNVX'),
       (21, 'Ngân hàng TMCP Quân đội', 'MB', '970422', 'MBBank', 'https://api.vietqr.io/img/MB.png', 1, 1, 3,
        1, 'MSCBVNVX'),
       (38, 'Ngân hàng TMCP Kỹ thương Việt Nam', 'TCB', '970407', 'Techcombank', 'https://api.vietqr.io/img/TCB.png', 1,
        1, 3, 1, 'VTCBVNVX'),
       (2, 'Ngân hàng TMCP Á Châu', 'ACB', '970416', 'ACB', 'https://api.vietqr.io/img/ACB.png', 1, 1, 3, 1,
        'ASCBVNVX'),
       (47, 'Ngân hàng TMCP Việt Nam Thịnh Vượng', 'VPB', '970432', 'VPBank', 'https://api.vietqr.io/img/VPB.png', 1, 1,
        3, 1, 'VPBKVNVX'),
       (39, 'Ngân hàng TMCP Tiên Phong', 'TPB', '970423', 'TPBank', 'https://api.vietqr.io/img/TPB.png', 1, 1,
        3, 1, 'TPBVVNVX'),
       (36, 'Ngân hàng TMCP Sài Gòn Thương Tín', 'STB', '970403', 'Sacombank', 'https://api.vietqr.io/img/STB.png', 1,
        1, 3, 1, 'SGTTVNVX'),
       (12, 'Ngân hàng TMCP Phát triển Thành phố Hồ Chí Minh', 'HDB', '970437', 'HDBank',
        'https://api.vietqr.io/img/HDB.png', 1, 1, 3, 1, 'HDBCVNVX'),
       (44, 'Ngân hàng TMCP Bản Việt', 'VCCB', '970454', 'VietCapitalBank', 'https://api.vietqr.io/img/VCCB.png', 1,
        1, 3, 1, 'VCBCVNVX'),
       (31, 'Ngân hàng TMCP Sài Gòn', 'SCB', '970429', 'SCB', 'https://api.vietqr.io/img/SCB.png', 1, 1, 3, 1,
        'SACLVNVX'),
       (45, 'Ngân hàng TMCP Quốc tế Việt Nam', 'VIB', '970441', 'VIB', 'https://api.vietqr.io/img/VIB.png', 1, 1,
        3, 1, 'VNIBVNVX'),
       (35, 'Ngân hàng TMCP Sài Gòn - Hà Nội', 'SHB', '970443', 'SHB', 'https://api.vietqr.io/img/SHB.png', 1, 1,
        3, 1, 'SHBAVNVX'),
       (10, 'Ngân hàng TMCP Xuất Nhập khẩu Việt Nam', 'EIB', '970431', 'Eximbank', 'https://api.vietqr.io/img/EIB.png',
        1, 1, 3, 1, 'EBVIVNVX'),
       (22, 'Ngân hàng TMCP Hàng Hải', 'MSB', '970426', 'MSB', 'https://api.vietqr.io/img/MSB.png', 1, 1, 3,
        1, 'MCOBVNVX'),
       (53, 'TMCP Việt Nam Thịnh Vượng - Ngân hàng số CAKE by VPBank', 'CAKE', '546034', 'CAKE',
        'https://api.vietqr.io/img/CAKE.png', 1, 1, 3, 1, NULL),
       (54, 'TMCP Việt Nam Thịnh Vượng - Ngân hàng số Ubank by VPBank', 'Ubank', '546035', 'Ubank',
        'https://api.vietqr.io/img/UBANK.png', 1, 1, 3, 1, NULL),
       (58, 'Ngân hàng số Timo by Ban Viet Bank (Timo by Ban Viet Bank)', 'TIMO', '963388', 'Timo',
        'https://vietqr.net/portal-service/resources/icons/TIMO.png', 1, 0, 0, 1, NULL),
       (57, 'Tổng Công ty Dịch vụ số Viettel - Chi nhánh tập đoàn công nghiệp viễn thông Quân Đội', 'VTLMONEY',
        '971005', 'ViettelMoney', 'https://api.vietqr.io/img/VIETTELMONEY.png', 0, 1, 0, 0, NULL),
       (56, 'VNPT Money', 'VNPTMONEY', '971011', 'VNPTMoney', 'https://api.vietqr.io/img/VNPTMONEY.png', 0, 1,
        0, 0, NULL),
       (34, 'Ngân hàng TMCP Sài Gòn Công Thương', 'SGICB', '970400', 'SaigonBank',
        'https://api.vietqr.io/img/SGICB.png', 1, 1, 3, 1, 'SBITVNVX'),
       (3, 'Ngân hàng TMCP Bắc Á', 'BAB', '970409', 'BacABank', 'https://api.vietqr.io/img/BAB.png', 1, 1,
        3, 1, 'NASCVNVX'),
       (30, 'Ngân hàng TMCP Đại Chúng Việt Nam', 'PVCB', '970412', 'PVcomBank',
        'https://api.vietqr.io/img/PVCB.png', 1, 1, 3, 1, 'WBVNVNVX'),
       (27, 'Ngân hàng Thương mại TNHH MTV Đại Dương', 'Oceanbank', '970414', 'Oceanbank',
        'https://api.vietqr.io/img/OCEANBANK.png', 1, 1, 3, 1, 'OCBKUS3M'),
       (24, 'Ngân hàng TMCP Quốc Dân', 'NCB', '970419', 'NCB', 'https://api.vietqr.io/img/NCB.png', 1, 1, 3, 1,
        'NVBAVNVX'),
       (37, 'Ngân hàng TNHH MTV Shinhan Việt Nam', 'SHBVN', '970424', 'ShinhanBank',
        'https://api.vietqr.io/img/SHBVN.png', 1, 1, 3, 1, 'SHBKVNVX'),
       (1, 'Ngân hàng TMCP An Bình', 'ABB', '970425', 'ABBANK', 'https://api.vietqr.io/img/ABB.png', 1, 1, 3,
        1, 'ABBKVNVX'),
       (41, 'Ngân hàng TMCP Việt Á', 'VAB', '970427', 'VietABank', 'https://api.vietqr.io/img/VAB.png', 1, 1,
        3, 1, 'VNACVNVX'),
       (23, 'Ngân hàng TMCP Nam Á', 'NAB', '970428', 'NamABank', 'https://api.vietqr.io/img/NAB.png', 1, 1,
        3, 1, 'NAMAVNVX'),
       (29, 'Ngân hàng TMCP Xăng dầu Petrolimex', 'PGB', '970430', 'PGBank', 'https://api.vietqr.io/img/PGB.png', 1, 1,
        3, 1, 'PGBLVNVX'),
       (46, 'Ngân hàng TMCP Việt Nam Thương Tín', 'VIETBANK', '970433', 'VietBank',
        'https://api.vietqr.io/img/VIETBANK.png', 1, 1, 3, 1, 'VNTTVNVX'),
       (5, 'Ngân hàng TMCP Bảo Việt', 'BVB', '970438', 'BaoVietBank', 'https://api.vietqr.io/img/BVB.png', 1, 1,
        3, 1, 'BVBVVNVX'),
       (33, 'Ngân hàng TMCP Đông Nam Á', 'SEAB', '970440', 'SeABank', 'https://api.vietqr.io/img/SEAB.png', 1, 1,
        3, 1, 'SEAVVNVX'),
       (52, 'Ngân hàng Hợp tác xã Việt Nam', 'COOPBANK', '970446', 'COOPBANK', 'https://api.vietqr.io/img/COOPBANK.png',
        1, 1, 3, 1, NULL),
       (20, 'Ngân hàng TMCP Lộc Phát Việt Nam', 'LPB', '970449', 'LPBank', 'https://api.vietqr.io/img/LPB.png', 1, 1,
        3, 1, 'LVBKVNVX'),
       (19, 'Ngân hàng TMCP Kiên Long', 'KLB', '970452', 'KienLongBank', 'https://api.vietqr.io/img/KLB.png', 1, 1,
        3, 1, 'KLBKVNVX'),
       (55, 'Ngân hàng Đại chúng TNHH Kasikornbank', 'KBank', '668888', 'KBank', 'https://api.vietqr.io/img/KBANK.png',
        1, 1, 3, 1, 'KASIVNVX'),
       (50, 'Ngân hàng Kookmin - Chi nhánh Hà Nội', 'KBHN', '970462', 'KookminHN', 'https://api.vietqr.io/img/KBHN.png',
        0, 0, 0, 0, NULL),
       (60, 'Ngân hàng KEB Hana – Chi nhánh Thành phố Hồ Chí Minh', 'KEBHANAHCM', '970466', 'KEBHanaHCM',
        'https://api.vietqr.io/img/KEBHANAHCM.png', 0, 0, 0, 0, NULL),
       (61, 'Ngân hàng KEB Hana – Chi nhánh Hà Nội', 'KEBHANAHN', '970467', 'KEBHANAHN',
        'https://api.vietqr.io/img/KEBHANAHN.png', 0, 0, 0, 0, NULL),
       (62, 'Công ty Tài chính TNHH MTV Mirae Asset (Việt Nam) ', 'MAFC', '977777', 'MAFC',
        'https://api.vietqr.io/img/MAFC.png', 0, 0, 0, 0, NULL),
       (59, 'Ngân hàng Citibank, N.A. - Chi nhánh Hà Nội', 'CITIBANK', '533948', 'Citibank',
        'https://api.vietqr.io/img/CITIBANK.png', 0, 0, 0, 0, NULL),
       (51, 'Ngân hàng Kookmin - Chi nhánh Thành phố Hồ Chí Minh', 'KBHCM', '970463', 'KookminHCM',
        'https://api.vietqr.io/img/KBHCM.png', 0, 0, 0, 0, NULL),
       (63, 'Ngân hàng Chính sách Xã hội', 'VBSP', '999888', 'VBSP', 'https://api.vietqr.io/img/VBSP.png', 0, 0,
        0, 0, NULL),
       (49, 'Ngân hàng TNHH MTV Woori Việt Nam', 'WVN', '970457', 'Woori', 'https://api.vietqr.io/img/WVN.png', 1, 1,
        0, 1, NULL),
       (48, 'Ngân hàng Liên doanh Việt - Nga', 'VRB', '970421', 'VRB', 'https://api.vietqr.io/img/VRB.png', 0, 1,
        0, 0, NULL),
       (40, 'Ngân hàng United Overseas - Chi nhánh TP. Hồ Chí Minh', 'UOB', '970458', 'UnitedOverseas',
        'https://api.vietqr.io/img/UOB.png', 0, 1, 0, 0, NULL),
       (32, 'Ngân hàng TNHH MTV Standard Chartered Bank Việt Nam', 'SCVN', '970410', 'StandardChartered',
        'https://api.vietqr.io/img/SCVN.png', 0, 1, 0, 0, 'SCBLVNVX'),
       (28, 'Ngân hàng TNHH MTV Public Việt Nam', 'PBVN', '970439', 'PublicBank', 'https://api.vietqr.io/img/PBVN.png',
        0, 1, 0, 0, 'VIDPVNVX'),
       (25, 'Ngân hàng Nonghyup - Chi nhánh Hà Nội', 'NHB HN', '801011', 'Nonghyup',
        'https://api.vietqr.io/img/NHB.png', 0, 0, 0, 0, NULL),
       (18, 'Ngân hàng TNHH Indovina', 'IVB', '970434', 'IndovinaBank', 'https://api.vietqr.io/img/IVB.png', 0, 1,
        0, 0, NULL),
       (16, 'Ngân hàng Công nghiệp Hàn Quốc - Chi nhánh TP. Hồ Chí Minh', 'IBK - HCM', '970456', 'IBKHCM',
        'https://api.vietqr.io/img/IBK.png', 0, 0, 0, 0, NULL),
       (15, 'Ngân hàng Công nghiệp Hàn Quốc - Chi nhánh Hà Nội', 'IBK - HN', '970455', 'IBKHN',
        'https://api.vietqr.io/img/IBK.png', 0, 0, 0, 0, NULL),
       (14, 'Ngân hàng TNHH MTV HSBC (Việt Nam)', 'HSBC', '458761', 'HSBC', 'https://api.vietqr.io/img/HSBC.png', 0, 1,
        0, 0, 'HSBCVNVX'),
       (13, 'Ngân hàng TNHH MTV Hong Leong Việt Nam', 'HLBVN', '970442', 'HongLeong',
        'https://api.vietqr.io/img/HLBVN.png', 0, 1, 0, 0, 'HLBBVNVX'),
       (11, 'Ngân hàng Thương mại TNHH MTV Dầu Khí Toàn Cầu', 'GPB', '970408', 'GPBank',
        'https://api.vietqr.io/img/GPB.png', 0, 1, 0, 0, 'GBNKVNVX'),
       (9, 'Ngân hàng TMCP Đông Á', 'DOB', '970406', 'DongABank', 'https://api.vietqr.io/img/DOB.png', 0, 1,
        0, 0, 'EACBVNVX'),
       (8, 'DBS Bank Ltd - Chi nhánh Thành phố Hồ Chí Minh', 'DBS', '796500', 'DBSBank',
        'https://api.vietqr.io/img/DBS.png', 0, 0, 0, 0, 'DBSSVNVX'),
       (7, 'Ngân hàng TNHH MTV CIMB Việt Nam', 'CIMB', '422589', 'CIMB', 'https://api.vietqr.io/img/CIMB.png', 1, 1,
        0, 1, 'CIBBVNVN'),
       (6, 'Ngân hàng Thương mại TNHH MTV Xây dựng Việt Nam', 'CBB', '970444', 'CBBank',
        'https://api.vietqr.io/img/CBB.png', 0, 1, 0, 0, 'GTBAVNVX');


insert into wallet (id, type, balance, version)
values (-1, 'USER', 1000000000, 0);