openapi: 3.0.3
info:
  title: EWallet API Description
  description: Đây là API mô tả cho dự án EWallet
  version: 1.0.0

servers:
  - url: 'https://api.htilssu.com/'
    variables:
      version:
        default: 'v1'
        description: 'API version'
paths:
  '/api/v1/refund':
    get:
      tags:
        - transaction
      description: New endpoint
      responses:
        400:
          description: Giao dịch không thành công do không tồn tại hoặc giao dịch đó chưa được thanh toán
          content:
            application/json:
              example:               {
                "transaction": {
                  "money": 1.0,
                  "currency": "VND",
                  "transactionType": "transfer",
                  "transactionTarget": "wallet",
                  "status": "PENDING",
                  "created": "2024-07-25T15:56:57.629Z",
                  "updated": "2024-07-25T15:56:57.629Z",
                  "id": "100000000000106"
                },
                "message": "Giao dịch đang chờ xử lý"
              }



  /api/v1/user/:
    get:
      tags:
        - user
      summary: "GET api/v1/user/"
      operationId: "getUser"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              example: {
                "id": "1000000002",
                "firstName": "Thanh Tùng",
                "lastName": "Nguyễn",
                "email": "test@test.com",
                "userName": "ntt1234",
                "avatar": null,
                "dob": "2004-08-08",
                "isActive": false,
                "isVerified": false,
                "gender": true,
                "created": "2024-07-24",
                "address": "838 Sư Vạn Hạnh",
                "phoneNumber": "0477189739",
                "job": "Engineer"
              }
  /auth/login:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      tags:
        - auth
      description: endpoint dùng để đăng nhập vào hệ thống
      responses:
        401:
          description: Đăng nhập không thành công
          content:
            application/json:
              schema:
                default:
                  {
                    "message": "Mật khẩu không đúng"
                  }
        200:
          description: Đăng nhập thành công
          content:
            application/json:
              schema:
                default:
                  {
                    "user": {
                      "id": "1000000002",
                      "firstName": "Thanh Tùng",
                      "lastName": "Nguyễn",
                      "email": "test@test.com",
                      "userName": "ntt1234",
                      "avatar": null,
                      "dob": "2004-08-08",
                      "isActive": false,
                      "isVerified": false,
                      "gender": true,
                      "created": "2024-07-24",
                      "address": "838 Sư Vạn Hạnh",
                      "phoneNumber": "0477189739",
                      "job": "Engineer"
                    },
                    "message": "Đăng nhập thành công",
                    "token": "eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJzdWIiOiIxMDAwMDAwMDAyIiwiaWQiOiIxMDAwMDAwMDAyIiwiZmlyc3ROYW1lIjoiVGhhbmggVMO5bmciLCJsYXN0TmFtZSI6Ik5ndXnhu4VuIiwiZW1haWwiOiJ0ZXN0QHRlc3QuY29tIiwidXNlck5hbWUiOiJudHQxMjM0IiwiYXZhdGFyIjpudWxsLCJwYXNzd29yZCI6bnVsbCwiZG9iIjpbMjAwNCw4LDhdLCJpc0FjdGl2ZSI6ZmFsc2UsImlzVmVyaWZpZWQiOmZhbHNlLCJnZW5kZXIiOnRydWUsImNyZWF0ZWQiOlsyMDI0LDcsMjRdLCJwYXJ0bmVyIjpudWxsLCJhZGRyZXNzIjoiODM4IFPGsCBW4bqhbiBI4bqhbmgiLCJwaG9uZU51bWJlciI6IjA0NzcxODk3MzkiLCJqb2IiOiJFbmdpbmVlciIsImV4cCI6MTcyMjA2NzU5OH0."
                  }
