CREATE TABLE permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    CONSTRAINT pk_permissions PRIMARY KEY (id),
    CONSTRAINT uc_permissions_name UNIQUE (name)
);

CREATE TABLE role_permissions (
    role_id INTEGER NOT NULL,
    permission_id BIGINT NOT NULL,
    CONSTRAINT pk_role_permissions PRIMARY KEY (role_id, permission_id),
    CONSTRAINT fk_role_permissions_role FOREIGN KEY (role_id) REFERENCES role (id),
    CONSTRAINT fk_role_permissions_permission FOREIGN KEY (permission_id) REFERENCES permissions (id)
);

INSERT INTO role (id, name) VALUES (1, 'Admin') ON CONFLICT (id) DO NOTHING;
INSERT INTO role (id, name) VALUES (2, 'Manager') ON CONFLICT (id) DO NOTHING;
INSERT INTO role (id, name) VALUES (3, 'User') ON CONFLICT (id) DO NOTHING;

INSERT INTO permissions (name, description) VALUES ('MANAGE_USERS', 'Quyền quản lý người dùng') ON CONFLICT (name) DO NOTHING;
INSERT INTO permissions (name, description) VALUES ('VIEW_DATA', 'Quyền xem dữ liệu') ON CONFLICT (name) DO NOTHING;
INSERT INTO permissions (name, description) VALUES ('EDIT_DATA', 'Quyền chỉnh sửa dữ liệu') ON CONFLICT (name) DO NOTHING;
INSERT INTO permissions (name, description) VALUES ('ALL_ACCESS', 'Quyền truy cập tất cả') ON CONFLICT (name) DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id) VALUES (1, (SELECT id FROM permissions WHERE name = 'ALL_ACCESS')) ON CONFLICT DO NOTHING;
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, (SELECT id FROM permissions WHERE name = 'MANAGE_USERS')) ON CONFLICT DO NOTHING;
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, (SELECT id FROM permissions WHERE name = 'VIEW_DATA')) ON CONFLICT DO NOTHING;
INSERT INTO role_permissions (role_id, permission_id) VALUES (3, (SELECT id FROM permissions WHERE name = 'VIEW_DATA')) ON CONFLICT DO NOTHING;

ALTER TABLE "user"
ADD COLUMN role_id INTEGER,
ADD CONSTRAINT fk_user_role FOREIGN KEY (role_id) REFERENCES role (id);