# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy

on:
  push:
    branches:
      - 'releases/**'
      - release
      - main
  workflow_dispatch:

jobs:
  test:
    environment: Production
    runs-on: ubuntu-latest
    name: Testing
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4.3.0
        with:
          cache: "gradle"
          java-version: '21'
          distribution: 'corretto'

      - name: Build with Gradle
        run: ./gradlew build

      - name: run test
        run: |
          chmod +x gradlew
          ./gradlew test

  build:
    environment: Production
    runs-on: ubuntu-latest
    needs:
      - test
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          cache: "gradle"
          java-version: '21'
          distribution: 'corretto'

      - name: Build with Gradle Wrapper
        run: |
          chmod +x gradlew
          ./gradlew clean build --exclude-task test


  docker-image:
    environment: Production
    needs: test
    runs-on: ubuntu-latest
    name: Docker Image

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: set up secret
        run: echo "${{ secrets.ENV }}" > "${{ github.workspace }}/src/main/resources/env.properties"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./
          push: true
          tags: htilssu/ewallet-springboot:latest
  deploy:
    name: deploy
    needs: docker-image
    runs-on: self-hosted
    steps:
      - name: pull image
        run: sudo docker pull htilssu/ewallet-springboot:latest

      - name: rm docker container
        run: sudo docker rm -f ewallet || true

      - name: Run container
        run: sudo docker run --name ewallet -d -p 8080:8080 htilssu/ewallet-springboot:latest

      - name: prune image
        run: sudo docker image prune -f
